import Activity from './Activity';
import Book from './Book';
import Bookmark from './Bookmark';
import BookOpen from './BookOpen';
import Box from './Box';
import Briefcase from './Briefcase';
import Check from './Check';
import CheckCircle from './CheckCircle';
import Clipboard from './Clipboard';
import Clock from './Clock';
import Copy from './Copy';
import Cross from './Cross';
import Edit from './Edit';
import ExternalLink from './ExternalLink';
import Eye from './Eye';
import Filter from './Filter';
import Home from './Home';
import Icon from './Icon';
import Key from './Key';
import Link from './Link';
import Logout from './Logout';
import Plus from './Plus';
import RefreshCw from './RefreshCw';
import Search from './Search';
import Tag from './Tag';
import Trash from './Trash';
import User from './User';
import Users from './Users';

Icon.Activity = Activity;
Icon.Book = Book;
Icon.Bookmark = Bookmark;
Icon.BookOpen = BookOpen;
Icon.Box = Box;
Icon.Briefcase = Briefcase;
Icon.Check = Check;
Icon.CheckCircle = CheckCircle;
Icon.Clipboard = Clipboard;
Icon.Clock = Clock;
Icon.Copy = Copy;
Icon.Cross = Cross;
Icon.Edit = Edit;
Icon.ExternalLink = ExternalLink;
Icon.Eye = Eye;
Icon.Filter = Filter;
Icon.Home = Home;
Icon.Key = Key;
Icon.Link = Link;
Icon.Logout = Logout;
Icon.Plus = Plus;
Icon.RefreshCw = RefreshCw;
Icon.Search = Search;
Icon.Tag = Tag;
Icon.Trash = Trash;
Icon.User = User;
Icon.Users = Users;

export default Icon;
